import {test,expect} from '@playwright/test'

for(const width of [320,390,1440]){
 test(`built public routes and reload at ${width}`,async({page})=>{
  await page.setViewportSize({width,height:1000})
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
  await page.route('**/api/auth/session',route=>route.fulfill({status:401,body:''}))
  for(const path of ['/','/customers/','/suppliers/','/work/','/participate/','/login','/register','/register/','/register/index.html','/cabinet/','/cabinet/work/','/cabinet/settings/','/cabinet/organizations/']){
   await page.goto(path);await expect(page.locator('h1')).toBeVisible()
   await page.reload();await expect(page.locator('h1')).toBeVisible()
   const publicLogo=page.locator('header.site-header .brand img')
   if(await publicLogo.count()) expect(await publicLogo.evaluate(image=>image.getBoundingClientRect().width)).toBe(width<768?192:256)
   await expect(page.locator('a[href="/register"]')).toHaveCount(0)
   if(path.startsWith('/register')) await expect(page).toHaveURL(/\/login$/)
   expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  }
  expect(errors).toEqual([])
 })
 test(`built Sber button stays green while checking and after a provider click at ${width}`,async({page})=>{
  await page.setViewportSize({width,height:1000})
  let releaseSession!:()=>void;const sessionHeld=new Promise<void>(resolve=>{releaseSession=resolve})
  let navigationAttempts=0
  await page.route('**/api/auth/session',async route=>{await sessionHeld;await route.fulfill({status:401,body:''})})
  page.on('dialog',async dialog=>{
   expect(dialog.type()).toBe('beforeunload');navigationAttempts++;await dialog.dismiss()
  })
  try{
   await page.goto('/')
   const forumAction=page.getByRole('link',{name:'Начать работу',exact:true,includeHidden:true})
   await expect(forumAction).toHaveCSS('background-color','rgb(255, 85, 26)')
   await page.locator('.site-header').getByRole('link',{name:'Войти',exact:true}).click()
   const sber=page.getByRole('button',{name:'Войти по Сбер ID',exact:true})
   await expect(sber).toBeDisabled()
   for(const property of ['background-color','border-top-color'])await expect(sber).toHaveCSS(property,'rgb(33, 160, 56)')
   await expect(sber).toHaveCSS('color','rgb(255, 255, 255)')
   releaseSession();await expect(sber).toBeEnabled()
   await sber.hover();await expect(sber).toHaveCSS('background-color','rgb(30, 144, 50)')
   // Cancel only the browser's document departure so the real click handler's
   // disabled/redirecting state stays inspectable without contacting Sber.
   await page.evaluate(()=>window.addEventListener('beforeunload',event=>{event.preventDefault();event.returnValue=''}))
   await sber.click({noWaitAfter:true})
   await expect.poll(()=>navigationAttempts).toBe(1)
   await expect(sber).toBeDisabled()
   await expect(page.getByRole('status')).toHaveText('Переходим к Сбер ID…')
   for(const property of ['background-color','border-top-color'])await expect(sber).toHaveCSS(property,'rgb(33, 160, 56)')
   await expect(sber).toHaveCSS('color','rgb(255, 255, 255)')
   await expect(forumAction).toHaveCSS('background-color','rgb(255, 85, 26)')
   await expect(page).toHaveURL(/\/login$/)
   await page.keyboard.press('Enter');expect(navigationAttempts).toBe(1)
  }finally{releaseSession()}
 })
 for(const entry of ['Войти','Начать работу']){
  test(`built held 200 ${entry} history and focus at ${width}`,async({page})=>{
   await page.setViewportSize({width,height:1000})
   let release!:()=>void;const held=new Promise<void>(resolve=>{release=resolve});let requests=0
   await page.route('**/api/auth/session',async route=>{requests++;await held;await route.fulfill({status:200,json:{user:{id:'synthetic',displayName:'Synthetic'}}})})
   const background='/?campaign=built#rules'
   await page.goto(background)
   await page.locator('h1').evaluate(node=>node.setAttribute('data-original-home','yes'))
   const opener=entry==='Войти'?page.locator('.site-header').getByRole('link',{name:'Войти',exact:true}):page.getByRole('link',{name:'Начать работу',exact:true})
   await opener.click()
   await expect(page.getByRole('dialog',{name:'Войти в аккаунт',exact:true})).toBeVisible()
   await expect(page.getByRole('dialog').getByRole('link',{name:'Зарегистрироваться',exact:true})).toHaveCount(0)
   await expect(page).toHaveURL(/\/login$/)
   release()
   await expect(page.getByRole('dialog').getByText('Вы уже вошли в аккаунт')).toBeVisible()
   await expect(page.locator('.site-header')).toContainText('В кабинет')
   await expect(page.locator('#hero-title')).toHaveAttribute('data-original-home','yes')
   expect(requests).toBe(1)
   await page.getByRole('button',{name:'Закрыть окно'}).click()
   await expect(page).toHaveURL(new RegExp('/\\?campaign=built#rules$'))
   await expect.poll(()=>page.evaluate(()=>document.activeElement instanceof HTMLElement && document.activeElement!==document.body && document.activeElement.isConnected)).toBe(true)
   await page.goForward();await expect(page.getByRole('dialog')).toBeVisible()
   await expect(page.locator('#hero-title')).toHaveAttribute('data-original-home','yes')
   await page.goBack();await expect(page.getByRole('dialog')).toHaveCount(0)
   await page.goForward();await page.reload()
   await expect(page.getByRole('dialog')).toBeVisible()
   await expect(page.locator('#hero-title')).toContainText('Заказы, исполнители и работа в строительстве')
   expect(await page.evaluate(()=>history.state.publicAuthBackground)).toBe(background)
   await page.getByRole('button',{name:'Закрыть окно'}).click()
   await expect.poll(()=>page.evaluate(()=>document.activeElement instanceof HTMLElement && document.activeElement!==document.body)).toBe(true)
  })
 }
 test(`built entry CTAs open the shared login at ${width}`,async({page})=>{
  await page.setViewportSize({width,height:1000})
  await page.route('**/api/auth/session',route=>route.fulfill({status:401,body:''}))
  for(const [path,label,count] of [
   ['/','Начать работу',1],['/customers/','Разместить заказ',2],
   ['/suppliers/','Найти заказы',2],['/suppliers/','Приступить к работе',4],
   ['/work/','Найти работу',2],['/work/','Выбрать заказы',1],['/work/','Выбрать вакансии',1],
  ] as const){
   await page.goto(path)
   const openers=page.getByRole(path==='/'?'link':'button',{name:label,exact:true})
   await expect(openers).toHaveCount(count)
   for(let index=0;index<count;index++){
    const opener=openers.nth(index)
    await opener.click()
    await expect(page.getByRole('dialog',{name:'Войти в аккаунт',exact:true})).toBeVisible()
    await expect(page.getByRole('dialog')).toHaveCount(1)
    await expect(page).toHaveURL(/\/login$/)
    await expect(page.getByRole('button',{name:'Войти по Сбер ID',exact:true})).toBeEnabled()
    await page.getByRole('button',{name:'Закрыть окно',exact:true}).click()
    await expect(page).toHaveURL(new URL(path,page.url()).href)
    await expect(opener).toBeFocused()
   }
  }
 })
}
for(const status of [401,500])test(`built guest and unknown ${status}`,async({page})=>{
 await page.route('**/api/auth/session',route=>route.fulfill({status,body:''}))
 await page.goto('/login?auth_error=sber_unavailable')
 await expect(page.getByText(status===401?'Вход через Сбер ID пока недоступен':'Не удалось проверить вход. Повторите попытку')).toBeVisible()
 await expect(page.getByRole('button',{name:'Войти по Сбер ID'})).toBeDisabled()
})
test('built cabinet uses a confirmed session and blocked callback opens a support dialog',async({page})=>{
 await page.route('**/api/auth/session',route=>route.fulfill({status:200,json:{user:{id:'synthetic-person',displayName:'Тестовый пользователь'},roles:['individual']}}))
 await page.route('**/api/profile',route=>route.fulfill({status:200,json:{userId:'synthetic-person',profile:{email:'owner@example.test'}}}))
 await page.goto('/cabinet/?auth=success')
 await expect(page.getByRole('heading',{name:'Личные данные',exact:true,level:1})).toBeVisible()
 await expect(page.getByText('owner@example.test',{exact:true})).toBeVisible()
 await expect(page.getByRole('link',{name:'Тестовый пользователь',exact:true})).toBeVisible()
 await expect(page.getByText('Физлицо',{exact:true})).toHaveCount(0)
 await expect(page.getByRole('banner').getByRole('button',{name:'Выйти',exact:true})).toBeVisible()
 await expect(page.locator('footer.profile-footer')).toHaveCount(0)
 await page.goto('/?auth_error=account_deactivated')
 const blocked=page.getByRole('dialog',{name:'Вы заблокированы на платформе',exact:true})
 await expect(blocked).toBeVisible()
 await expect(blocked.getByRole('link',{name:'Тех. поддержка'})).toHaveAttribute('href','mailto:info@astforum.ru')
 await expect(blocked.getByRole('button',{name:'Войти по Сбер ID'})).toHaveCount(0)
})
for(const width of [320,390,1440])test(`built personal profile, work, reload and logout at ${width}`,async({page})=>{
 await page.setViewportSize({width,height:1000})
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
 let loggedIn=true
 await page.route('**/api/auth/session',route=>route.fulfill(loggedIn?{status:200,json:{user:{id:'owner',displayName:'Анна Иванова'},roles:['individual']}}:{status:401,body:''}))
 await page.route('**/api/profile',route=>route.fulfill(loggedIn?{status:200,json:{userId:'owner',profile:{email:'owner@example.test',place_of_work:'Реальное место работы'}}}:{status:401,body:''}))
 await page.route('**/api/auth/logout',route=>{loggedIn=false;return route.fulfill({status:204})})
 await page.goto('/cabinet/?auth=success')
 await expect(page.getByRole('heading',{name:'Личные данные',exact:true,level:1})).toBeVisible()
 await expect(page.getByText('owner@example.test',{exact:true})).toBeVisible()
 await expect(page.getByText(/Демонстрационный профиль|Смирнов|Вымышленные данные/)).toHaveCount(0)
 await page.reload();await expect(page.getByText('owner@example.test',{exact:true})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 if(width<768)await page.getByRole('button',{name:'Открыть меню профиля'}).click()
 await page.getByRole('link',{name:'Работа',exact:true}).filter({visible:true}).click()
 await expect(page).toHaveURL(/\/cabinet\/work\/#main$/)
 await expect(page.getByText('Реальное место работы',{exact:true})).toBeVisible()
 await page.reload();await expect(page.getByRole('heading',{name:'Работа',level:1,exact:true})).toBeVisible()
 await expect(page.getByRole('banner').getByRole('button',{name:'Выйти',exact:true})).toBeVisible()
 await expect(page.locator('footer.profile-footer')).toHaveCount(0)
 const accountLogo=page.locator('.account-brand img')
 await expect(accountLogo).toBeVisible()
 expect(await accountLogo.evaluate(image=>image.getBoundingClientRect().width)).toBe(width<768?192:256)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByRole('button',{name:'Выйти',exact:true}).click()
 await expect(page).toHaveURL(new URL('/',page.url()).href)
 await page.goto('/cabinet/')
 await expect(page).toHaveURL(new URL('/',page.url()).href)
 await expect(page.locator('.site-header').getByRole('link',{name:'Войти',exact:true})).toBeVisible()
 await expect(page.getByText('owner@example.test',{exact:true})).toHaveCount(0)
 expect(errors).toEqual([])
})
for(const width of [320,390,1440])test(`built settings toggle persists and remains accessible at ${width}`,async({page})=>{
 await page.setViewportSize({width,height:1000})
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
 let enabled=false
 await page.route('**/api/auth/session',route=>route.fulfill({status:200,json:{user:{id:'owner',displayName:'Анна Иванова'},roles:['individual']}}))
 await page.route('**/api/profile',route=>route.fulfill({status:200,json:{userId:'owner',profile:{email:'owner@example.test'}}}))
 await page.route('**/api/settings',route=>{
  if(route.request().method()==='PUT')enabled=route.request().postDataJSON().workAsIndividual
  return route.fulfill({status:200,json:{userId:'owner',workAsIndividual:enabled}})
 })
 await page.goto('/cabinet/')
 if(width<768)await page.getByRole('button',{name:'Открыть меню профиля'}).click()
 await page.getByRole('link',{name:'Настройки',exact:true}).filter({visible:true}).click()
 await expect(page).toHaveURL(/\/cabinet\/settings\/#main$/)
 await expect(page.getByRole('heading',{name:'Настройки',level:1,exact:true})).toBeVisible()
 const logout=page.getByRole('banner').getByRole('button',{name:'Выйти',exact:true})
 await expect(logout).toBeVisible()
 await expect(logout).toHaveText('')
 await expect(page.getByRole('button',{name:'Выйти',exact:true})).toHaveCount(1)
 await expect(page.locator('footer.profile-footer')).toHaveCount(0)
 await expect(page.getByText('Физлицо',{exact:true})).toHaveCount(0)
 await expect(page.getByRole('link',{name:'На главную',exact:true})).toHaveCount(0)
 const checkbox=page.getByRole('checkbox',{name:'Хочу работать на площадке как физическое лицо',exact:true})
 await expect(page.getByRole('checkbox')).toHaveCount(1)
 await checkbox.focus();await page.keyboard.press('Space')
 await expect(checkbox).toBeChecked();await expect(checkbox).toBeEnabled()
 await expect(page.getByText('Сохранено',{exact:true})).toHaveCount(0)
 await page.reload();await expect(checkbox).toBeChecked()
 // Controlled state stays at the confirmed choice until the PUT completes.
 await checkbox.click()
 await expect(checkbox).not.toBeChecked()
 await expect(checkbox).toBeEnabled()
 await expect(page.getByText('Сохранено',{exact:true})).toHaveCount(0)
 await page.reload();await expect(checkbox).not.toBeChecked()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 expect(errors).toEqual([])
})
for(const width of [320,390,1440])test(`built logout returns home and reopens standard login at ${width}`,async({page})=>{
 await page.setViewportSize({width,height:1000})
 let loggedIn=true;let logoutRequests=0
 await page.route('**/api/auth/session',route=>route.fulfill(loggedIn ? {status:200,json:{user:{id:'synthetic-person',displayName:'Тестовый пользователь'},roles:['individual']}} : {status:401,body:''}))
 await page.route('**/api/profile',route=>route.fulfill(loggedIn?{status:200,json:{userId:'synthetic-person',profile:{email:'owner@example.test'}}}:{status:401,body:''}))
 await page.route('**/api/auth/logout',route=>{
  if(route.request().method()!=='POST')return route.fulfill({status:405,body:''})
  logoutRequests++;loggedIn=false;return route.fulfill({status:204,body:''})
 })
 await page.route('**/auth/sber-id/start?intent=login',route=>route.fulfill({status:200,contentType:'text/html',body:'<h1>Provider entry fixture</h1>'}))
 // Keep an earlier cabinet document in history to exercise the guest guard.
 await page.goto('/cabinet/')
 await expect(page.getByRole('link',{name:'Тестовый пользователь',exact:true})).toBeVisible()
 await page.goto('/cabinet/?auth=success')
 await expect(page.getByRole('heading',{name:'Личные данные',exact:true,level:1})).toBeVisible()
 // The header logout stays visible while the long personal profile is scrolled.
 // Preserve that starting position so replacing the URL alone cannot satisfy
 // the homepage scroll-reset contract.
 await expect(page.getByText('owner@example.test',{exact:true})).toBeVisible()
 await page.evaluate(()=>window.scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}))
 expect(await page.evaluate(()=>window.scrollY)).toBeGreaterThan(0)
 await page.getByRole('button',{name:'Выйти',exact:true}).click()
 await expect(page).toHaveURL(new URL('/',page.url()).href)
 await expect(page.getByRole('heading',{name:'Заказы, исполнители и работа в строительстве',exact:true})).toBeVisible()
 await expect.poll(()=>page.evaluate(()=>({x:window.scrollX,y:window.scrollY}))).toEqual({x:0,y:0})
 await expect(page.locator('.site-header').getByRole('link',{name:'Войти',exact:true})).toBeVisible()
 await expect(page.getByRole('link',{name:'Тестовый пользователь',exact:true})).toHaveCount(0)
 await expect(page.getByText('Физлицо',{exact:true})).toHaveCount(0)
 await expect(page.getByText('Войдите через Сбер ID, чтобы открыть личный кабинет',{exact:true})).toHaveCount(0)
 expect(logoutRequests).toBe(1)
 await page.goBack()
 await expect(page).toHaveURL(new URL('/',page.url()).href)
 await expect(page.getByRole('heading',{name:'Личный кабинет',exact:true})).toHaveCount(0)
 await page.reload()
 await expect(page.locator('.site-header').getByRole('link',{name:'Войти',exact:true})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.locator('.site-header').getByRole('link',{name:'Войти',exact:true}).click()
 const login=page.getByRole('dialog',{name:'Войти в аккаунт',exact:true})
 await expect(login).toBeVisible();await expect(page).toHaveURL(/\/login$/)
 await expect(login.getByText('Вы уже вошли в аккаунт')).toHaveCount(0)
 await login.getByRole('button',{name:'Войти по Сбер ID',exact:true}).click()
 await expect(page).toHaveURL(/\/auth\/sber-id\/start\?intent=login$/)
})
test('built unavailable cabinet stays until a confirmed guest response returns it home',async({page})=>{
 let unavailable=true
 await page.route('**/api/auth/session',route=>route.fulfill({status:unavailable?503:401,body:''}))
 await page.goto('/cabinet/?auth=success')
 await expect(page.getByText('Не удалось проверить вход',{exact:true})).toBeVisible()
 await expect(page).toHaveURL(/\/cabinet\/$/)
 unavailable=false;await page.getByRole('button',{name:'Повторить',exact:true}).click()
 await expect(page).toHaveURL(new URL('/',page.url()).href)
 await expect(page.getByRole('heading',{name:'Заказы, исполнители и работа в строительстве',exact:true})).toBeVisible()
})
test('built failed logout retains the person and can be retried successfully',async({page})=>{
 let loggedIn=true;let denyLogout=true
 await page.route('**/api/auth/session',route=>route.fulfill(loggedIn ? {status:200,json:{user:{id:'synthetic-person',displayName:'Тестовый пользователь'},roles:['individual']}} : {status:401,body:''}))
 await page.route('**/api/profile',route=>route.fulfill(loggedIn?{status:200,json:{userId:'synthetic-person',profile:{email:'owner@example.test'}}}:{status:401,body:''}))
 await page.route('**/api/auth/logout',route=>{
  if(denyLogout)return route.fulfill({status:503,body:''})
  loggedIn=false;return route.fulfill({status:204,body:''})
 })
 await page.goto('/cabinet/')
 await page.getByRole('button',{name:'Выйти',exact:true}).click()
 await expect(page.getByText('Не удалось выйти. Повторите попытку',{exact:true})).toBeVisible()
 await expect(page).toHaveURL(/\/cabinet\/$/)
 await expect(page.getByRole('link',{name:'Тестовый пользователь',exact:true})).toBeVisible()
 denyLogout=false;await page.getByRole('button',{name:'Выйти',exact:true}).click()
 await expect(page).toHaveURL(new URL('/',page.url()).href)
 await expect(page.getByRole('link',{name:'Тестовый пользователь',exact:true})).toHaveCount(0)
})
test('built work carousel survives modal history and demo keeps its actual embed contract',async({page})=>{
 await page.route('**/api/auth/session',route=>route.fulfill({status:401,body:''}))
 await page.route('https://cal.astforum.ru/**',route=>route.fulfill({status:200,contentType:'text/html',body:'<p>Isolated calendar fixture</p>'}))
 await page.goto('/work/#order-example')
 await page.getByRole('button',{name:'Следующий пример'}).click()
 await expect(page.locator('#work-example-slide')).toHaveAttribute('aria-label','2 из 2: Работа в штате')
 await page.locator('.site-header').getByRole('link',{name:'Войти',exact:true}).click()
 await page.getByRole('button',{name:'Закрыть окно'}).click()
 await expect(page).toHaveURL(/\/work\/#order-example$/)
 await expect(page.locator('#work-example-slide')).toHaveAttribute('aria-label','2 из 2: Работа в штате')
 await page.goForward();await expect(page.getByRole('dialog')).toBeVisible()
 await page.goBack();await expect(page.locator('#work-example-slide')).toHaveAttribute('aria-label','2 из 2: Работа в штате')
 await page.goto('/')
 await page.getByRole('button',{name:'Записаться на демо',exact:true}).first().click()
 const frame=page.locator('iframe[title="Cal.diy — запись на демонстрацию АСТ Форум"]')
 await expect(frame).toBeVisible()
 await expect(frame).toHaveAttribute('src',/^https:\/\/cal\.astforum\.ru\/.+\?embed=true&layout=month_view&theme=light$/)
 await expect(page.getByText('Загрузка календаря…')).toHaveCount(0)
})

for(const width of [320,390,768,1440])test(`built organizations save, reload, history and accessible scrolling at ${width}`,async({page})=>{
 await page.setViewportSize({width,height:1000})
 let saved=false
 const pending={id:'addition',inn:'9709128511',name:null,status:'pending',members:[]}
 await page.route('**/api/auth/session',route=>route.fulfill({status:200,json:{user:{id:'owner',displayName:'Анна Иванова'}}}))
 await page.route('**/api/profile',route=>route.fulfill({status:503,body:''}))
 await page.route('**/api/me/organizations',route=>{
  if(route.request().method()==='POST'){saved=true;return route.fulfill({status:201,json:{userId:'owner',item:pending}})}
  return route.fulfill({status:200,json:{userId:'owner',items:saved?[pending]:[],nextCursor:null}})
 })
 await page.goto('/cabinet/organizations/')
 await expect(page.getByRole('heading',{level:1,name:'Мои организации',exact:true})).toBeVisible()
 await page.getByLabel('ИНН',{exact:true}).fill('9709128511');await page.getByLabel('ИНН',{exact:true}).press('Enter')
 await expect(page.getByText('Организация сохранена',{exact:true})).toBeVisible()
 await expect(page.getByText('9709128511',{exact:true})).toBeVisible()
 await page.reload();await expect(page.getByText('9709128511',{exact:true})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await expect(page.getByRole('region',{name:'Мои организации',exact:true})).toHaveCount(width===1440?0:1)
 if(width<768)await page.getByRole('button',{name:'Открыть меню профиля'}).click()
 await page.getByRole('link',{name:'Работа',exact:true}).filter({visible:true}).click()
 await expect(page.getByRole('heading',{level:1,name:'Работа',exact:true})).toBeVisible()
 await page.goBack();await expect(page.getByText('9709128511',{exact:true})).toBeVisible()
 await page.goForward();await expect(page.getByRole('heading',{level:1,name:'Работа',exact:true})).toBeVisible()
})
